### ISSUE TITLE
problema na extração dos dados ao executar "get_corona()"

### ISSUE THREAD

**Issue by cassianord** [liibre/corona#10]
Olá, pessoal! Estou utilizando o pacote para atualizar um aplicativo (fantástico o trabalho de vocês, aliás), mas hj de manhã o aplicativo não consegue mais executar, devido a um erro na extração dos dados após executar a função `get_corona(filename = "corona_brasil01")`

```
Extraindo a url ...
Error in magrittr::extract2(., 12) : índice fora de limites
```

**Comment by saramortara** [comment]
Oi! Então, o site do minstério está fora do ar. Esse é um erro porque há uma falha na requisição mesmo... infelizmente não temos o que fazer agora. Talvez só melhorar a msg de erro :P

**Comment by cassianord** [comment]
Ah, uma pena! Vamos torcer que volte logo então. 
Sugestão: salvar no repositório uma base de backup, e carregá-la alternativamente pelo get_corona() quando o link do ministério estiver off. Seria bem útil em casos como o meu, quando o aplicativo deixa de rodar completamente se a função retorna com erro/sem os dados.  =)
De todo modo, obrigado!

**Comment by saramortara** [comment]
ótima ideia. aviso aqui quando funcionar com essa opção. Mas por enquanto, vc encontra o ultimo dado que baixamos em vignettes/output/

**Comment by saramortara** [comment]
optamos por não retornar os dados na função para manter um fluxo de trabalho coerente. De qualquer forma, os dados estão disponíveis em: https://github.com/liibre/coronabr/blob/master/vignettes/output/corona_brasil01.csv
