### ISSUE TITLE
Fonte do site do Min. da Saúde mudou

### ISSUE THREAD

**Issue by Freguglia** [liibre/corona#27]
Oi pessoal, estou mantendo um outro pacote apenas para importação dos dados (Ministério da Saúde, Brasil.io, CSSE da Johns Hopkins e vou adicionando conforme encontrar mais) em [Freguglia/datacovidbr](https://github.com/Freguglia/datacovidbr), sem nenhum tipo de análise pra minimizar o número de dependências.

Hoje o jeito que eu usava para importar os dados do ministério da saúde parou de funcionar (colocar a data de trás pra frente no nome do arquivo a cada dia), e acredito que o do `coronabr` ([aqui](https://github.com/liibre/coronabr/blob/get_corona/R/get_corona_minsaude.R)) também era isso.

Eu consegui consertar ele [aqui](https://github.com/Freguglia/datacovidbr/blob/master/R/ministeriosaude.R), se quiserem aproveitar pra não gastar muito tempo olhando coisas em javascript, o endereço para o arquivo `.csv` do dia fica em
```
  library(httr)
  library(magrittr)
  link <- GET("https://xx9p7hp1p7.execute-api.us-east-1.amazonaws.com/prod/PortalGeral",
              add_headers("X-Parse-Application-Id" = 
                            "unAFkcaNDeXajurGB7LChj8SgQYS2ptm")) %>%
    content() %>%
    '[['("results") %>%
    '[['(1) %>%
    '[['("arquivo") %>%
    '[['("url")
```
Posso escrever pra vocês sempre que notar uma mudança drástica ou também se quiserem utilizar o outro pacote para a parte da importação podemos ir coordenando.

Victor.

**Comment by AndreaSanchezTapia** [comment]
Obrigada Victor, e parabéns pelo pacote

percebemos que o ministério mudou o padrão (de novo), mesmo que a url pro GET seja a mesma que o @jtrecenti tinha encontrado para a versão anterior do site. 

Na mudança mais recente as datas estão vindo no padrão de cinco números do Excel (com a origem dia 01/01/1900). Dá para corrigir isto com julian() e a origem que o Excel usa, mas é bem capaz de voltar a mudar, então desta vez vamos esperar um par de dias ¬¬

**Comment by Freguglia** [comment]
Esse padrão de data mudaram no arquivo das 17h de hoje pelo jeito, porque durante a tarde ainda estava funcionando :(

Como preciso manter sempre o outro repo atualizado porque tem gente usando pra trabalhar na modelagem, eu vou tentar ir acompanhando as mudanças que eles fazem na API. Se ficar uma coisa consistente por alguns dias eu mando um PR no branch daqui com a versão mais recente funcionando :)

Vou fechar aqui por enquanto.
