### ISSUE TITLE
Suggestion: examples and functions given

### ISSUE THREAD

**Issue by samuel-carleial** [liibre/corona#32]
Notei que a seccao "como usar" poderia ser um pouco mais detalhada. Existem exemplos que na verdade estao na seccao "artigos" e pra mim parece um pouco confuso esse titulo. Talvez voces devessem renomeá-la em "exemplos".

**Comment by samuel-carleial** [comment]
De qualquer maneira, acho essa iniciativa muito interessante da parte dos desenvolvedores. Gostaria de poder contribuir com esse projeto e poderia revisar os exemplos dados, dando uma melhor formatada. Posso fazer pull requests dos textos que vejo que podem ser melhorados?

**Comment by kguidonimartins** [comment]
Xs desenvolvedorxs discutiram ativamente a estrutura do site deste pacote. Contudo, sugestões são bem-vindas. Veja como contribuir [aqui](https://github.com/liibre/coronabr/blob/master/CONTRIBUTING.md).
