### ISSUE TITLE
Requisitos do pacote

### ISSUE THREAD

**Issue by samuel-carleial** [liibre/corona#34]
Acho que seria interessante destacar que para o pacote rodar é preciso instalar dentre alguns pacotes de R também ImageMagick no computador. Isso nao está tao evidente a primeira vista. 

Assim, acho que a documentacao melhoraria, se os pacotes (dependencias) de R e ImageMagick fossem enlistados no README ou num arquivo a parte na pagina principal

**Comment by kguidonimartins** [comment]
Oi Samuel, sem dúvida podemos melhorar vários aspectos do pacote. PRs são bem vindos! Veja [aqui](https://github.com/liibre/coronabr/blob/master/CONTRIBUTING.md) como contribuir. 

Sobre a dependência do ImageMagick: até o mesmo o [`{magick}`](https://github.com/ropensci/magick#installation) tem dependências externas. Repare no README dele que, dependendo do sistema operacional, a forma de instalação difere. 

Agradecemos por reportar o problema. Você poderia incluir aqui o resultado do comando `sessionInfo()` para o reporte ficar completo?
