### ISSUE TITLE
Problema com a instalação do pacote brazilmaps necessário para instalar o coronabr

### ISSUE THREAD

**Issue by Utreti** [liibre/corona#36]
```
Downloading GitHub repo liibre/coronabr@master
Skipping 1 packages not available: brazilmaps
Installing 32 packages: brazilmaps, gganimate, gifski, janitor, sf, tmap, webshot, e1071, lwgeom, stars, units, raster, classInt, dichromat, leaflet.providers, leaflet, mapdeck, colourvalues, googlePolylines, geojsonsf, jsonify, shiny, sfheaders, rapidjsonr, spatialwidget, sourcetools, fastmap, tweenr, snakecase, tmaptools, leafsync, leafem
Installing packages into ‘/home/embryous/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Error: Failed to install 'coronabr' from GitHub:
  (converted from warning) package ‘brazilmaps’ is not available (for R version 3.6.3)
```
O pacote brazilmaps se faz necessário para a instalação do pacote mas ele não está disponível para a minha versão do R, haveria alguma alternativa a isso?

**Comment by kguidonimartins** [comment]
Olá, uma das alternativas é atualizar sua versão do R.

**Comment by Utreti** [comment]
Você diz para o R(4.0.0)? O pacote foi removido do repositório e justamente achei que seria o contrário e ele não funcionaria para versões mais novas do R

**Comment by Utreti** [comment]
Bem, achei o problema caso mais alguém esteja com o R 3.6.3 e esteja num Ubuntu 18.04, nao sei como é para quem possui outros sistemas operacionais mas o principal problema é o fato do brazilmaps não estar mais no repositório Cran.
Logo é necessário fazer a instalação do pacote brazilmaps manualmento pelo devtols e isso requer a instalação de outros pacotes de maneira manual.
Os pacotes necessários são: units, sf, lwgeom e outras possíveis dependências necessárias para o Linux se elas não estiverem instaladas. Como o libgdal-dev que é instalado com o comando sudo apt install libgdal-dev.
O lwgeom pode possuir erros na instalação pelo install.packages() também entao é necessário instalar o pacote através do github.

**Comment by kguidonimartins** [comment]
> Você diz para o R(4.0.0)? O pacote foi removido do repositório e justamente achei que seria o contrário e ele não funcionaria para versões mais novas do R

Isso não funcionaria para este caso em específico; o [`{brazilmaps}`](https://cran.r-project.org/web/packages/brazilmaps/index.html) foi retirado do CRAN há exatos 15 dias. 

Agradecemos por reportar o problema. De fato, cada SO tem suas próprias dependências. Os erros de instalação de alguns pacotes para o R oferecem avisos sobre as dependências para alguns SOs. Infelizmente, isso não é verdade para todos SOs. 

Para o registro do problema ficar completo, você poderia informar o resultado do comando `sessionInfo()`?

**Comment by Utreti** [comment]
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C               LC_TIME=pt_BR.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pt_BR.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=pt_BR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=pt_BR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3
