### ISSUE TITLE
error in file(con r ) invalid 'description' argument

### ISSUE THREAD

**Issue by raspereira** [liibre/corona#46]
Eu vinha usando o pacote no Win 10 para baixar os dados do ministério da saúde. De umas semana pra cá está dando esse erro no 'file(con.....'.

> get_corona_minsaude()
Baixando dados do Min. da Saude...
Error in file(con, "r") : argumento 'description' inválido
Além disso: Warning message:
In unzip(xlsxFile, exdir = xmlDir) :
  erro 1 na extração a partir de arquivo zip

**Comment by AndreaSanchezTapia** [comment]
Obrigada pelo aviso, o formato do arquivo mudou de novo e agora é um .csv dentro de um ZIP. A mudança requer a instalação do pacote **vroom** para ler rapidamente esse cvs.

**Comment by raspereira** [comment]
Obrigado pelo retorno!
Instalei o pacote vroom e continuou dando erro. Preciso reinstalar o coronabr?


--
Rodrigo A. S. Pereira
Depto de Biologia/FFCLRP-USP
Av. Bandeirantes, 3900
14040-901 - Ribeirão Preto, SP
Fone: +55 16 3315-4678
Fax: +55 16 3315-9101
http://sites.ffclrp.usp.br/ficus/ 

    Em segunda-feira, 26 de outubro de 2020 21:28:10 BRT, AndreaSanchezTapia <notifications@github.com> escreveu:  
 
 


Obrigada pelo aviso, o formato do arquivo mudou de novo e agora é um .csv dentro de um ZIP. A mudança requer a instalação do pacote vroom para ler rapidamente esse cvs.

**Comment by AndreaSanchezTapia** [comment]
Sim, você precisa instalar de novo o pacote.
