### ISSUE TITLE
Automating daily data download and pkgdown build

### ISSUE THREAD

**Issue by kguidonimartins** [liibre/corona#6]
Hi ladies, thanks for this package! This is really useful!

Are you downloading the data and building the pkgdown site by hand? Maybe I can implement this workflow with travis-ci. What do you think?

**Comment by saramortara** [comment]
That would be amazing Karlo! We built in the fastest way that was not the most elegant... but first we need to do a few things:
- encapsulate the graphic code in functions
- organize the vignettes workflow
Lets do this and then we can work on the makefile
